version: '3.1'

services:

  bot:
    build: .
    depends_on: 
      - db
    volumes: 
      - ./src:/app

  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: corona
    ports: 
        - 5432:5432
